// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        (unknown)
// source: giraffe/gateway/v1/http.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HttpAnonymous struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *HttpAnonymous) Reset() {
	*x = HttpAnonymous{}
	if protoimpl.UnsafeEnabled {
		mi := &file_giraffe_gateway_v1_http_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HttpAnonymous) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HttpAnonymous) ProtoMessage() {}

func (x *HttpAnonymous) ProtoReflect() protoreflect.Message {
	mi := &file_giraffe_gateway_v1_http_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HttpAnonymous.ProtoReflect.Descriptor instead.
func (*HttpAnonymous) Descriptor() ([]byte, []int) {
	return file_giraffe_gateway_v1_http_proto_rawDescGZIP(), []int{0}
}

type HttpEmployee struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Codes []string `protobuf:"bytes,1,rep,name=codes,proto3" json:"codes,omitempty"`
}

func (x *HttpEmployee) Reset() {
	*x = HttpEmployee{}
	if protoimpl.UnsafeEnabled {
		mi := &file_giraffe_gateway_v1_http_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HttpEmployee) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HttpEmployee) ProtoMessage() {}

func (x *HttpEmployee) ProtoReflect() protoreflect.Message {
	mi := &file_giraffe_gateway_v1_http_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HttpEmployee.ProtoReflect.Descriptor instead.
func (*HttpEmployee) Descriptor() ([]byte, []int) {
	return file_giraffe_gateway_v1_http_proto_rawDescGZIP(), []int{1}
}

func (x *HttpEmployee) GetCodes() []string {
	if x != nil {
		return x.Codes
	}
	return nil
}

type HttpUser struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Codes []string `protobuf:"bytes,1,rep,name=codes,proto3" json:"codes,omitempty"`
}

func (x *HttpUser) Reset() {
	*x = HttpUser{}
	if protoimpl.UnsafeEnabled {
		mi := &file_giraffe_gateway_v1_http_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HttpUser) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HttpUser) ProtoMessage() {}

func (x *HttpUser) ProtoReflect() protoreflect.Message {
	mi := &file_giraffe_gateway_v1_http_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HttpUser.ProtoReflect.Descriptor instead.
func (*HttpUser) Descriptor() ([]byte, []int) {
	return file_giraffe_gateway_v1_http_proto_rawDescGZIP(), []int{2}
}

func (x *HttpUser) GetCodes() []string {
	if x != nil {
		return x.Codes
	}
	return nil
}

var File_giraffe_gateway_v1_http_proto protoreflect.FileDescriptor

var file_giraffe_gateway_v1_http_proto_rawDesc = []byte{
	0x0a, 0x1d, 0x67, 0x69, 0x72, 0x61, 0x66, 0x66, 0x65, 0x2f, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61,
	0x79, 0x2f, 0x76, 0x31, 0x2f, 0x68, 0x74, 0x74, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x12, 0x67, 0x69, 0x72, 0x61, 0x66, 0x66, 0x65, 0x2e, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79,
	0x2e, 0x76, 0x31, 0x22, 0x0f, 0x0a, 0x0d, 0x48, 0x74, 0x74, 0x70, 0x41, 0x6e, 0x6f, 0x6e, 0x79,
	0x6d, 0x6f, 0x75, 0x73, 0x22, 0x24, 0x0a, 0x0c, 0x48, 0x74, 0x74, 0x70, 0x45, 0x6d, 0x70, 0x6c,
	0x6f, 0x79, 0x65, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x6f, 0x64, 0x65, 0x73, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x09, 0x52, 0x05, 0x63, 0x6f, 0x64, 0x65, 0x73, 0x22, 0x20, 0x0a, 0x08, 0x48, 0x74,
	0x74, 0x70, 0x55, 0x73, 0x65, 0x72, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x6f, 0x64, 0x65, 0x73, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x05, 0x63, 0x6f, 0x64, 0x65, 0x73, 0x42, 0x14, 0x5a, 0x12,
	0x67, 0x69, 0x72, 0x61, 0x66, 0x66, 0x65, 0x2f, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x2f,
	0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_giraffe_gateway_v1_http_proto_rawDescOnce sync.Once
	file_giraffe_gateway_v1_http_proto_rawDescData = file_giraffe_gateway_v1_http_proto_rawDesc
)

func file_giraffe_gateway_v1_http_proto_rawDescGZIP() []byte {
	file_giraffe_gateway_v1_http_proto_rawDescOnce.Do(func() {
		file_giraffe_gateway_v1_http_proto_rawDescData = protoimpl.X.CompressGZIP(file_giraffe_gateway_v1_http_proto_rawDescData)
	})
	return file_giraffe_gateway_v1_http_proto_rawDescData
}

var file_giraffe_gateway_v1_http_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_giraffe_gateway_v1_http_proto_goTypes = []interface{}{
	(*HttpAnonymous)(nil), // 0: giraffe.gateway.v1.HttpAnonymous
	(*HttpEmployee)(nil),  // 1: giraffe.gateway.v1.HttpEmployee
	(*HttpUser)(nil),      // 2: giraffe.gateway.v1.HttpUser
}
var file_giraffe_gateway_v1_http_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_giraffe_gateway_v1_http_proto_init() }
func file_giraffe_gateway_v1_http_proto_init() {
	if File_giraffe_gateway_v1_http_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_giraffe_gateway_v1_http_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HttpAnonymous); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_giraffe_gateway_v1_http_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HttpEmployee); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_giraffe_gateway_v1_http_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HttpUser); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_giraffe_gateway_v1_http_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_giraffe_gateway_v1_http_proto_goTypes,
		DependencyIndexes: file_giraffe_gateway_v1_http_proto_depIdxs,
		MessageInfos:      file_giraffe_gateway_v1_http_proto_msgTypes,
	}.Build()
	File_giraffe_gateway_v1_http_proto = out.File
	file_giraffe_gateway_v1_http_proto_rawDesc = nil
	file_giraffe_gateway_v1_http_proto_goTypes = nil
	file_giraffe_gateway_v1_http_proto_depIdxs = nil
}
