// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        (unknown)
// source: giraffe/common/v1/user.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UserType int32

const (
	UserType_USER_TYPE_UNSPECIFIED UserType = 0
	UserType_USER_TYPE_ANONYMOUS   UserType = 1
	UserType_USER_TYPE_EMPLOYEE    UserType = 2
	UserType_USER_TYPE_USER        UserType = 3
)

// Enum value maps for UserType.
var (
	UserType_name = map[int32]string{
		0: "USER_TYPE_UNSPECIFIED",
		1: "USER_TYPE_ANONYMOUS",
		2: "USER_TYPE_EMPLOYEE",
		3: "USER_TYPE_USER",
	}
	UserType_value = map[string]int32{
		"USER_TYPE_UNSPECIFIED": 0,
		"USER_TYPE_ANONYMOUS":   1,
		"USER_TYPE_EMPLOYEE":    2,
		"USER_TYPE_USER":        3,
	}
)

func (x UserType) Enum() *UserType {
	p := new(UserType)
	*p = x
	return p
}

func (x UserType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (UserType) Descriptor() protoreflect.EnumDescriptor {
	return file_giraffe_common_v1_user_proto_enumTypes[0].Descriptor()
}

func (UserType) Type() protoreflect.EnumType {
	return &file_giraffe_common_v1_user_proto_enumTypes[0]
}

func (x UserType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use UserType.Descriptor instead.
func (UserType) EnumDescriptor() ([]byte, []int) {
	return file_giraffe_common_v1_user_proto_rawDescGZIP(), []int{0}
}

type AuthUser struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Type UserType `protobuf:"varint,2,opt,name=type,proto3,enum=giraffe.common.v1.UserType" json:"type,omitempty"`
}

func (x *AuthUser) Reset() {
	*x = AuthUser{}
	if protoimpl.UnsafeEnabled {
		mi := &file_giraffe_common_v1_user_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AuthUser) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthUser) ProtoMessage() {}

func (x *AuthUser) ProtoReflect() protoreflect.Message {
	mi := &file_giraffe_common_v1_user_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthUser.ProtoReflect.Descriptor instead.
func (*AuthUser) Descriptor() ([]byte, []int) {
	return file_giraffe_common_v1_user_proto_rawDescGZIP(), []int{0}
}

func (x *AuthUser) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *AuthUser) GetType() UserType {
	if x != nil {
		return x.Type
	}
	return UserType_USER_TYPE_UNSPECIFIED
}

var File_giraffe_common_v1_user_proto protoreflect.FileDescriptor

var file_giraffe_common_v1_user_proto_rawDesc = []byte{
	0x0a, 0x1c, 0x67, 0x69, 0x72, 0x61, 0x66, 0x66, 0x65, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e,
	0x2f, 0x76, 0x31, 0x2f, 0x75, 0x73, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x11,
	0x67, 0x69, 0x72, 0x61, 0x66, 0x66, 0x65, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x76,
	0x31, 0x22, 0x4b, 0x0a, 0x08, 0x41, 0x75, 0x74, 0x68, 0x55, 0x73, 0x65, 0x72, 0x12, 0x0e, 0x0a,
	0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x12, 0x2f, 0x0a,
	0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1b, 0x2e, 0x67, 0x69,
	0x72, 0x61, 0x66, 0x66, 0x65, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x76, 0x31, 0x2e,
	0x55, 0x73, 0x65, 0x72, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x2a, 0x6a,
	0x0a, 0x08, 0x55, 0x73, 0x65, 0x72, 0x54, 0x79, 0x70, 0x65, 0x12, 0x19, 0x0a, 0x15, 0x55, 0x53,
	0x45, 0x52, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46,
	0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x17, 0x0a, 0x13, 0x55, 0x53, 0x45, 0x52, 0x5f, 0x54, 0x59,
	0x50, 0x45, 0x5f, 0x41, 0x4e, 0x4f, 0x4e, 0x59, 0x4d, 0x4f, 0x55, 0x53, 0x10, 0x01, 0x12, 0x16,
	0x0a, 0x12, 0x55, 0x53, 0x45, 0x52, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x45, 0x4d, 0x50, 0x4c,
	0x4f, 0x59, 0x45, 0x45, 0x10, 0x02, 0x12, 0x12, 0x0a, 0x0e, 0x55, 0x53, 0x45, 0x52, 0x5f, 0x54,
	0x59, 0x50, 0x45, 0x5f, 0x55, 0x53, 0x45, 0x52, 0x10, 0x03, 0x42, 0x27, 0x5a, 0x25, 0x67, 0x69,
	0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x67, 0x69, 0x72, 0x61, 0x66, 0x66, 0x65,
	0x31, 0x30, 0x31, 0x2f, 0x61, 0x70, 0x69, 0x73, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x73,
	0x2f, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_giraffe_common_v1_user_proto_rawDescOnce sync.Once
	file_giraffe_common_v1_user_proto_rawDescData = file_giraffe_common_v1_user_proto_rawDesc
)

func file_giraffe_common_v1_user_proto_rawDescGZIP() []byte {
	file_giraffe_common_v1_user_proto_rawDescOnce.Do(func() {
		file_giraffe_common_v1_user_proto_rawDescData = protoimpl.X.CompressGZIP(file_giraffe_common_v1_user_proto_rawDescData)
	})
	return file_giraffe_common_v1_user_proto_rawDescData
}

var file_giraffe_common_v1_user_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_giraffe_common_v1_user_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_giraffe_common_v1_user_proto_goTypes = []interface{}{
	(UserType)(0),    // 0: giraffe.common.v1.UserType
	(*AuthUser)(nil), // 1: giraffe.common.v1.AuthUser
}
var file_giraffe_common_v1_user_proto_depIdxs = []int32{
	0, // 0: giraffe.common.v1.AuthUser.type:type_name -> giraffe.common.v1.UserType
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_giraffe_common_v1_user_proto_init() }
func file_giraffe_common_v1_user_proto_init() {
	if File_giraffe_common_v1_user_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_giraffe_common_v1_user_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AuthUser); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_giraffe_common_v1_user_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_giraffe_common_v1_user_proto_goTypes,
		DependencyIndexes: file_giraffe_common_v1_user_proto_depIdxs,
		EnumInfos:         file_giraffe_common_v1_user_proto_enumTypes,
		MessageInfos:      file_giraffe_common_v1_user_proto_msgTypes,
	}.Build()
	File_giraffe_common_v1_user_proto = out.File
	file_giraffe_common_v1_user_proto_rawDesc = nil
	file_giraffe_common_v1_user_proto_goTypes = nil
	file_giraffe_common_v1_user_proto_depIdxs = nil
}
